language: node_js
node_js:
  - '0.10'
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'jsontl' ]; then cd .. && eval "mv $currentfolder jsontl" && cd jsontl; fi
before_script:
	- node node_modules/.bin/mocha
